run:
  tests: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - copyloopvar
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomodguard
    - gosimple
    - gosec
    - govet
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - wsl

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable:
      - shadow
      - fieldalignment
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 31
  revive:
    rules:
      - name: unused-parameter
        disabled: false
        arguments:
          - allowRegex: "^_.*"
